version: "3.8"

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: referer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: dev-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: